c_compiler:
  - clang     # [osx]
  - vs2022    # [win]

cxx_compiler:
  - clangxx   # [osx]
  - vs2022    # [win]

cuda_compiler:
  - cuda-nvcc

cuda_compiler_version: # [not osx]
  - 12.8      # [not osx]

numpy:
  - 2.4.2

c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
  
c_stdlib_version:
  - "2.34"          # [linux]
