# change the version number in case of a release build
package:
  name: pychrono
  version: 8.0.0

source:
  path: ../../..

build:
  rpaths:
    - lib/

  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  binary_relocation: true
  
requirements:
  build:
    - python
    - cmake   # [not win]
    - ninja   # [linux or osx]
    - jinja2  # [linux]
    - libglvnd-glx-cos7-x86_64 # [linux]
    - freeglut # [linux]
    - libxxf86vm-devel-cos7-x86_64 # [linux]
    - swig
    - mkl-devel ==2020.0.0 # [not arm64]
    - irrlicht
    - occt ==7.4.0 # [not arm64]
    - numpy >=1.24.0
    - glew
    - glfw
    - eigen ==3.4.0

  run:
    - python
    - pythonocc-core ==7.4.0 # [py<=39 and not arm64]
    - mkl ==2020.0.0 # [not arm64]
    - numpy >=1.24.0
    - irrlicht
    - glew
    - glfw
    - eigen ==3.4.0

about:
  home: https://github.com/projectchrono/chrono
  license: BSD 3-Clause
  license_family: BSD
  summary: High performance library for multiphysics and multibody dynamics simulations
