# change the version number in case of a release build
package:
  name: pychrono
  version: 7.0.0

source:
  path: ../../..


build:
  rpaths:
    - lib/
  script_env:
    - CC
    - CXX
    - CI_PROJECT_DIR

  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  binary_relocation: true
  #features:
  #  - vc9               [win and py27]
  #  - vc14              [win and py35]
  #  - vc14              [win and py36]

requirements:
  build:
    - python
    - cmake >=3.9.3
    - swig >=4.0.0
    - mkl-devel
    - numpy >=1.16
    - glew
    - glfw

  run:
    - python
    - mkl
    - numpy >=1.16
    - glew
    - glfw

test:
  requires:
    - wxpython          [py27]
    - pyside            [py27]

about:
  home: https://github.com/projectchrono/chrono
  license: BSD 3-Clause
  license_family: BSD
  summary: A physics engine for constrained multi-flexible-body dynamics
