# change the version number in case of a release build
package:
  name: pychrono
  version: 9.0.1

source:
  path: ../../..

build:
  rpaths:
    - lib/

  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  binary_relocation: true
  
requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=4   # [not win]
    - ninja   # [linux or osx]
    - jinja2  # [linux]
    - swig ==4.0.2
    - git
    - cuda-toolkit ==12.8.0 # [not osx]
    - openmpi
    - intel-openmp ==2023.2.0 # [not arm64]
  host:
    - python
    - libglvnd-glx-cos7-x86_64 # [linux]
    - freeglut # [linux]
    - libxxf86vm-devel-cos7-x86_64 # [linux]
    - mkl-devel ==2023.2.0 # [not arm64]
    - irrlicht
    - opencascade ==7.4.0 # [not arm64]
    - numpy >=1.24.0
    - glew
    - glfw
    - eigen ==3.4.0
    - cuda-toolkit ==12.8.0 # [not osx]
    - urdfdom
    - urdfdom_headers
    - libgl-devel # [linux]
    - yaml
    - openmpi
    - intel-openmp ==2023.2.0 # [not arm64]
  run:
    - python
    - mkl ==2023.2.0 # [not arm64]
    - numpy >=1.24.0
    - irrlicht
    - opencascade ==7.4.0 # [not arm64]
    - glew
    - glfw
    - eigen ==3.4.0
    - cuda-toolkit ==12.8.0 # [not osx]
    - urdfdom
    - libgl # [linux]
    - openmpi
    - yaml

about:
  home: https://github.com/projectchrono/chrono
  license: BSD 3-Clause
  license_family: BSD
  summary: High performance library for multiphysics and multibody dynamics simulations
