# Sets the user, the work dir, and the command

USER ${USERNAME}
WORKDIR ${USERHOME}
ENV HOME=${USERHOME}
ENV USERSHELLPATH=${USERSHELLPATH}
ENV USERSHELLPROFILE=${USERSHELLPROFILE}

CMD ${USERSHELLPATH}
